<?xml version="1.0"?>
<!-- Revolute-Revolute Manipulator -->
<robot name="rrbot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="mass" value="1" /> <!-- arbitrary value for mass -->
  <xacro:property name="width" value="0.03" /> <!-- Square dimensions (widthxwidth) of beams -->
  <xacro:property name="height1" value="2.5" /> <!-- Link 1 -->
  <xacro:property name="height2" value="1" /> <!-- Link 2 -->
  <xacro:property name="height3" value="1" /> <!-- Link 3 -->
  <xacro:property name="camera_link" value="0.05" /> <!-- Size of square 'camera' box -->
  <xacro:property name="axel_offset" value="0.0" /> <!-- Space btw top of beam and the each joint -->

  <!-- Import all Gazebo-customization elements, including Gazebo colors -->
  <xacro:include filename="$(find rrbot_description)/urdf/rrbot_two.gazebo" />
  <!-- Import Rviz colors -->
  <xacro:include filename="$(find rrbot_description)/urdf/materials.xacro" />

  <!-- Used for fixing robot to Gazebo 'base_link' -->
  <link name="world"/>

  <joint name="fixed" type="fixed">
    <parent link="world"/>
    <child link="link1"/>
  </joint>

  <!-- Base Link -->
  <link name="link1">
    <collision>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <!--<visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>-->

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint1" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 ${width} ${height1 - axel_offset}" rpy="0 ${-0.5*PI} 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="10000" lower="${-PI*2.0}" upper="${PI*2.0}" velocity="1"/>
    <dynamics damping="0.1"/>
  </joint>

  <!-- Middle Link -->
  <link name="link2">
    <collision>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="1" ixy="0.0" ixz="0.0"
	  iyy="1" iyz="0.0"
	  izz="0"/>
    </inertial>
  </link>

  <joint name="joint2" type="continuous">
    <parent link="link2"/>
    <child link="link3"/>
    <origin xyz="0 ${width} ${height2 - axel_offset*2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="10000" lower="${-PI*2.0}" upper="${PI*2.0}" velocity="1"/>
    <dynamics damping="0.1"/>
  </joint>

  <!-- Top Link -->
  <link name="link3">
    <collision>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height3 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="1" ixy="0.0" ixz="0.0"
	  iyy="1" iyz="0.0"
	  izz="0"/>
    </inertial>
  </link>

  <transmission name="tran1">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>


<!-- copy one  -->

 <joint name="fixed_copy" type="fixed">
    <parent link="world"/>
    <child link="link1_copy"/>
    <origin xyz="0 0.92 0" rpy="0 0 ${PI}"/>
  </joint>

  <!-- Base Link -->
  <link name="link1_copy">
    <collision>
      <origin xyz="0 0.0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
    </collision>

    <!--<visual>
      <origin xyz="0 0 ${height1/2}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height1}"/>
      </geometry>
      <material name="orange"/>
    </visual>-->

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="${mass / 12.0 * (width*width + height1*height1)}" ixy="0.0" ixz="0.0"
	  iyy="${mass / 12.0 * (height1*height1 + width*width)}" iyz="0.0"
	  izz="${mass / 12.0 * (width*width + width*width)}"/>
    </inertial>
  </link>

  <joint name="joint1_copy" type="continuous">
    <parent link="link1_copy"/>
    <child link="link2_copy"/>
    <origin xyz="0 ${width} ${height1 - axel_offset}" rpy="0 ${0.5*PI} 0"/>
    <axis xyz="0 -1 0"/>
    <limit effort="10000" lower="${-PI*2.0}" upper="${PI*2.0}" velocity="1"/>
    <dynamics damping="0.1"/>
  </joint>

  <!-- Middle Link -->
  <link name="link2_copy">
    <collision>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height2/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height2}"/>
      </geometry>
      <material name="black"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height2 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="1" ixy="0.0" ixz="0.0"
	  iyy="1" iyz="0.0"
	  izz="0"/>
    </inertial>
  </link>

  <joint name="joint2_copy" type="continuous">
    <parent link="link2_copy"/>
    <child link="link3_copy"/>
    <origin xyz="0 ${width} ${height2 - axel_offset*2}" rpy="0 0 0"/>
    <axis xyz="0 -1 0"/>
    <limit effort="10000" lower="${-PI*2.0}" upper="${PI*2.0}" velocity="1"/>
    <dynamics damping="0.1"/>
  </joint>

  <!-- Top Link -->
  <link name="link3_copy">
    <collision>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 ${height3/2 - axel_offset}" rpy="0 0 0"/>
      <geometry>
	<box size="${width} ${width} ${height3}"/>
      </geometry>
      <material name="orange"/>
    </visual>

    <inertial>
      <origin xyz="0 0 ${height3 - axel_offset}" rpy="0 0 0"/>
      <mass value="${mass}"/>
      <inertia
	  ixx="1" ixy="0.0" ixz="0.0"
	  iyy="1" iyz="0.0"
	  izz="0"/>
    </inertial>
  </link>

  <link name="box">
    <visual>
      <origin xyz="0 0.37 0" rpy="0 0 0"/>
      <geometry>
	<box size="0.2 0.74 0.2"/>
      </geometry>
      <material name="brown"/>
    </visual>

    <inertial>
      <origin xyz="0 0.0 0" rpy="0 0 0"/>
      <mass value="10"/>
      <inertia
	  ixx="10" ixy="0.0" ixz="0.0"
	  iyy="10" iyz="0.0"
	  izz="0"/>
    </inertial>
  </link>

  <joint name="joint3" type="fixed">
    <parent link="link3"/>
    <child link="box"/>
    <origin xyz="0 ${width} ${height3 - axel_offset*2}" rpy="0 0 0"/>
  </joint>

  <link name="box_copy">
    <inertial>
      <origin xyz="0 0.0 0" rpy="0 0 0"/>
      <mass value="10"/>
      <inertia
	  ixx="10" ixy="0.0" ixz="0.0"
	  iyy="10" iyz="0.0"
	  izz="0"/>
    </inertial>
  </link>

  <joint name="joint3_copy" type="fixed">
    <parent link="link3_copy"/>
    <child link="box_copy"/>
    <origin xyz="0 ${width} ${height3 - axel_offset*2}" rpy="0 0 0"/>
  </joint>

  <transmission name="tran1_copy">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint1_copy">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor1_copy">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>

  <transmission name="tran2_copy">
    <type>transmission_interface/SimpleTransmission</type>
    <joint name="joint2_copy">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
    </joint>
    <actuator name="motor2_copy">
      <hardwareInterface>EffortJointInterface</hardwareInterface>
      <mechanicalReduction>1</mechanicalReduction>
    </actuator>
  </transmission>
</robot>
